### PR TITLE
Don't attempt to modify MAKEFLAGS in llvm-roc

### LINKED ISSUE #43: [llvm-roc] Uses too much RAM
# building LLVM/Clang requires ~1.5G per unit                               
    THREADS=$(( ($(getconf _PHYS_PAGES) * $(getconf PAGESIZE)) / 1610612736 ))  

Is quite wrong. My PC almost just died (was freezing like crazy because of swap storm). Ok, I've got 24 threads (AMD 3900x), so maybe some people get protected from this. Anyway, it was particularly nasty with the last link at 100%. Some ld tasks at the end take over 4GB of RAM.

With 4.5GB instead of 1.5, my system survived…

### PR DESCRIPTION
**Pull request by neeshy**
Users can always set this value in /etc/makepkg.conf or on the command line via MAKEFLAGS="-j8" makepkg
This fixes #43

### CODE REVIEW

**Comment by acxz** [comment]
Can we change the `pkgrel` here and add the .SRCINFO file? The commit we merge here will be the one we sync to the AUR.

**Comment by ranisalt** [comment]
This is dangerous. Compiling llvm requires **a lot** of memory and by a lot I mean over 1.5GB per core, as mentioned. If you have an 8 core machine with 8GB and run `make -j8` it will freeze to death.

**Comment by rigred** [comment]
Agreed the original code is sound. It checks if sufficient RAM is available and calculates the optimal build thread count.


1. $THREADS holds the maximum possible thread count calculated by dividing total system ram by required thread work unit size.
2. If $THREADS less than 1, build with a single thread.
3. Else if $THREADS greater than the number of processors, set Threads to the number of processor threads.
```
  THREADS=$(( ($(getconf _PHYS_PAGES) * $(getconf PAGESIZE)) / 1610612736 )) 
  cd "$srcdir/build"
    if [ "$THREADS" -lt 1 ]; then
        THREADS=1
    fi

    NPROC=$(nproc)
    if [ "$THREADS" -gt $(nproc) ]; then
        THREADS="$NPROC"
    fi
```

Really we should just include alternate logic for the debug build. which calculates for a bigger working site size per thread.

**Comment by neeshy** [comment]
>This is dangerous. Compiling llvm requires a lot of memory and by a lot I mean over 1.5GB per core, as mentioned. If you have an 8 core machine with 8GB and run make -j8 it will freeze to death.

I was just using -j8 as an example.

**Pull request closed without merging**
