### PR TITLE
[hcc(-git)] Delete hcc

### PR DESCRIPTION
**Pull request by tpkessler**
`hcc` is deprecated. The new `hip-rocclr` is now used for compiling GPU code, for instance `rocm-libs`.

### CODE REVIEW

**Comment by acxz** [comment]
We will keep rocm related packages in our source tree until they are also deleted from the AUR, if you could submit a deletion request for the `hcc-git` and `hcc` packages on the AUR (citing that you are a part of the rocm-arch [with link] group that maintains rocm related packages on the AUR) {sometimes it takes some convincing for a TU (trusted user) to delete an AUR package} that would be great.

**Comment by tpkessler** [comment]
I submitted deletion requests for hcc{,-git} and hip-hcc.

**Comment by ArchangeGabriel** [comment]
For what it’s worth, I’m remotely following your work here, because I’ll be interested in all this stack in the future. However since I’m quite busy already I don’t intend to bring it myself to [community], but might sponsor one of you (@acxz) to do so.

**Comment by tpkessler** [comment]
@ArchangeGabriel That's great news! Thank you very much for your interest in our work. Having ROCm in [community] would be amazing but unfortunately there's still a lot to do. Any testing and reporting is appreciated. 

@acxz : The packages hcc{,-git} and hip-hcc have been removed from the AUR. Can we now merge #190 #188 #191 ?

**Pull request merged**
