### PR TITLE
[rocm-device-libs] Replacing llvm-roc with llvm-amdgpu

### PR DESCRIPTION
**Pull request by helfio**
Hi,

This worked in my case.

Pablo.

### CODE REVIEW

**Comment by s-bernard** [comment]
You should probably get rid of the "Merge pull request" commit.

**Comment by helfio** [comment]
@s-bernard Sorry! I'm not used to this stuff. Is that ok now?

**Comment by s-bernard** [comment]
As you can see, only one commit in the PR, so yes! :smile:

**Comment by acxz** [comment]
Thx for the PR, @helfio !

**Pull request merged**
