### PR TITLE
upgpkg: migraphx 5.1.1-1

### PR DESCRIPTION
**Pull request by acxz**

### CODE REVIEW

**Comment by tpkessler** [comment]
Could you please update the package to 5.1.1?

**Comment by acxz** [comment]
It's been on my list, however, I'm currently having trouble upgrading the rest of the stack to 5.1, so holding off on updating till I can build the previous deps in chroot.

**Comment by acxz** [comment]
@tpkessler done

**Comment by tpkessler** [comment]
Thank you!

**Pull request merged**
