### PR TITLE
[roctracer] Successful build in clean chroot

### PR DESCRIPTION
**Pull request by tpkessler**
I had to patch the shell scripts that are cloned from a different repo during the configuration step. I don't know how far our directory structure follows AMD's, so I can't say if these patches are also needed upstream.

### CODE REVIEW

**Comment by acxz** [comment]
> I don't know how far our directory structure follows AMD's

Can you figure this out then? Will ensure that we are not patching an issue that could/should be fixed in another way.

**Comment by tpkessler** [comment]
I've removed the patches I added the before. But we still need the string header patch. I filed an upstream issue a few days ago: https://github.com/ROCmSoftwarePlatform/hsa-class/issues/1

**Comment by acxz** [comment]
Seems like you are missing the string header patch. Also if you could make an upstream PR about this, then we can pull this patch in straight from their github which would be ideal.

**Comment by tpkessler** [comment]
Hey @acxz the patch file is already included in our [repo](https://github.com/rocm-arch/rocm-arch/tree/master/roctracer)
What would be the advantage of pulling the patch from the upstream repo? Would we then cherry-pick a certain commit?

**Comment by acxz** [comment]
> patch file is already included in our repo
ah thx for pointing that out

> advantage of pulling the patch from the upstream
This ensures that we don't keep the work/improvement we made to ourselves but contribute back to upstream so that others can use

>Would we then cherry-pick a certain commit?
Essentially technically not a `cherry-pick`, but each commit is also a patch. So we just pull the commit as a patch from the internet and patch in a `prepare` function. See the following PKGBUILD as inspiration: https://github.com/acxz/pkgbuilds/blob/master/ignition-math/PKGBUILD
Notice how in the source we have another url for the patch instead of a local file.

**Comment by tpkessler** [comment]
That's pretty cool! I've opened a PR on the ROCm repo. We now fetch the patch file directly from GitHub.

**Pull request merged**
