### PR TITLE
Typo in description of dkms

### PR DESCRIPTION
**Pull request by aljazerzen**
I have no idea if this will break anything, merge wisely.

### CODE REVIEW

**Comment by acxz** [comment]
`rocm-dkms` is slated to be deleted as such closing this issue.

**Comment by aljazerzen** [comment]
Hey, this is still relevant. It only changes one work in the description.

**Comment by acxz** [comment]
@aljazerzen the package `rocm-dkms` does not exist.

**Comment by aljazerzen** [comment]
Oh, I though you were a bot :sweat_smile: 

Sorry for the noise I am producing and thank you for your efforts on rocm packaging!

**Pull request closed without merging**
