### PR TITLE
[hcc] Fix package description and remove CMAKE_BUILD_TYPE

### PR DESCRIPTION
**Pull request by tpkessler**
The package description for HCC is too long which breaks the syntax highlighting in vim.

### CODE REVIEW

**Comment by s-bernard** [comment]
12 commits for this seems odd. You probably need to create a new branch from master and cherry-pick the commit you really want.

**Comment by tpkessler** [comment]
Thanks @s-bernard, it's fixed now.

**Comment by s-bernard** [comment]
Way better! :) 

Still 2 thinks:
1. your commit description `Rebase against master` is not good. It does not give us any information about what/why it is doing. Something like "hcc: fix description for vim highlighting" should be better
2. you are actually bundling a change to hcc-git that you probably don't want.

**Comment by tpkessler** [comment]
> your commit description Rebase against master is not good.

Right. I changed the commit message

> you are actually bundling a change to hcc-git that you probably

We aim to remove all `CMAKE_BUILD_TYPE`s from the PKGBUILDs as the build type overwrites the user's custom CFLAGS. When I changed the description I also removed `CMAKE_BUILD_TYPE=Release`. I updated the title of the PR and the commit message.

**Comment by acxz** [comment]
thx for the comments @s-bernard , looks good now @tpkessler thx for the contribution!

**Pull request merged**
