### PR TITLE
Remove rocprofiler from dependencies

### LINKED ISSUE #49: [rocm-dev] Cyclic dependency
`rocprofiler` needs the meta package `rocm` which itself depends on `rocm-dev`, which among other, lists `rocprofiler` as a dependency. Is the `rocm-dev` package really needed?

### PR DESCRIPTION
**Pull request by tpkessler**
Fixes #49 

Relevant upstream discussion:
https://github.com/ROCm-Developer-Tools/rocprofiler/issues/18

### CODE REVIEW

**Comment by acxz** [comment]
Thx for the PR @tpkessler 

Although, before merging this PR, we need to make an upstream issue so this can be tracked. According to ArchLinux policy we gotta be as close to upstream as possible. If you can link an upstream issue to the corresponding issue on this repo that would be great!

Also, I am afraid that your PR is not up to spec. Please read up on the following: https://wiki.archlinux.org/index.php/PKGBUILD. Hint: Take a look at pkgrel, it should be incremented.

**Comment by tpkessler** [comment]
> Also, I am afraid that your PR is not up to spec. Please read up on the following: 

Good catch! I updated the PKGBUILD script.

> If you can link an upstream issue to the corresponding issue on this repo that would be great!

https://github.com/ROCm-Developer-Tools/rocprofiler/issues/18

**Comment by acxz** [comment]
Thx so much for your activisim, @tpkessler LGTM!

**Comment by acxz** [comment]
Thx for the upstream issue, the PR is still not up to snuff tho, Hint: .SRCINFO

**Comment by tpkessler** [comment]
Man, this is becoming awkward. Thanks for carefully checking my half-backed pull requests. I updated .SRCINFO.

**Comment by acxz** [comment]
Np man, I was like this once as well. We all learn with practice.
In any case, thx for the PR and the activisim! LGTM!

**Pull request merged**
