### PR TITLE
Fix rocalution checksum

### PR DESCRIPTION
**Pull request by nquest**
Rocalution checksum verification fails. Just fixed this.

### CODE REVIEW

**Comment by tpkessler** [comment]
Thanks for your PR! Please also update `.SRCINFO` and bump `pkgrel`:

**Review by acxz — CHANGES_REQUESTED** [review]
[pkgrel](https://wiki.archlinux.org/index.php/PKGBUILD#pkgrel)

[.SRCINFO](https://wiki.archlinux.org/index.php/.SRCINFO)

things to do to let AUR database know the package has updated.

**Comment by nquest** [comment]
Oh sorry, this is my first commit to community.

**Comment by nquest** [comment]
5 commits( Sorry. How make them all in one?

**Comment by tpkessler** [comment]
> Oh sorry, this is my first commit to community.

No problem! We all had to learn this at the beginning. I occasionally forget about this too. Let me quote from your README:

> For most packages, you have to update pkgver and sha256sums. Before you commit your changes you will need to generate .SRCINFO from the updated PKGBUILD:
```
makepkg --printsrcinfo > .SRCINFO
```
> and add it to your commit.

**Comment by acxz** [comment]
> 5 commits( Sorry. How make them all in one?

You can prob figure it out through here: https://gitbetter.substack.com/p/how-to-squash-git-commits

but don't worry about it, i'll squash it as I merge it.

Thanks for the contribution! Really appreciated it.

**Review by acxz — APPROVED** [review]

**Pull request merged**
