### PR TITLE
[rocm-opencl-runtime] Add OpenCL/vendors, fix ld.so.conf

### PR DESCRIPTION
**Pull request by tpkessler**
See also my PR #96

### CODE REVIEW

**Comment by tpkessler** [comment]
@ranisalt, please review.

**Comment by ranisalt** [comment]
I don't understand this change, to me it already installs that file to the specified location and this patch changes nothing. What am I doing wrong?q

**Comment by tpkessler** [comment]
Do you mean `amdocl64.icd`? If I don't put it under `/etc/OpenCL/vendors`, `clinfo` fails:
```
$ clinfo > /dev/null
ERROR: clGetPlatformIDs(-1001)
```
With the file at the right place, it works. Since
```
$ cat /etc/OpenCL/vendors/amdocl64.icd
libamdocl64.so
```
`/etc/ld.so.conf.d/rocm-opencl.conf` has to point to `/opt/rocm/lib/x86_64`:
```
$ ls /opt/rocm/lib/x86_64
libOpenCL.so  libOpenCL.so.1  libOpenCL.so.1.2  libamdocl64.so
```

**Comment by ranisalt** [comment]
But it is already there
```sh
$ pacman -Ql rocm-opencl-runtime
rocm-opencl-runtime /etc/
rocm-opencl-runtime /etc/OpenCL/
rocm-opencl-runtime /etc/OpenCL/vendors/
rocm-opencl-runtime /etc/OpenCL/vendors/amdocl64.icd
...
```

And `rocm-opencl-runtime` installs `libamdocl64.so` to `/opt/rocm/lib`. Also you probably don't want `libOpenCL.so` from this AMD, but rather the one from `ocl-icd`.

**Comment by tpkessler** [comment]
That's weird. I recompiled the package from the master branch:
```
$ tar tf rocm-opencl-runtime-3.3.0-2-x86_64.pkg.tar
.BUILDINFO
.MTREE
.PKGINFO
etc/
etc/ld.so.conf.d/
etc/ld.so.conf.d/rocm-opencl.conf
opt/
opt/rocm/
opt/rocm/bin/
opt/rocm/bin/x86_64/
opt/rocm/bin/x86_64/clinfo
opt/rocm/include/
opt/rocm/include/CL/
opt/rocm/include/CL/cl.h
opt/rocm/include/CL/cl.hpp
opt/rocm/include/CL/cl2.hpp
opt/rocm/include/CL/cl_ext.h
opt/rocm/include/CL/cl_gl.h
opt/rocm/include/CL/cl_gl_ext.h
opt/rocm/include/CL/cl_platform.h
opt/rocm/include/CL/opencl.h
opt/rocm/lib/
opt/rocm/lib/libOpenCL.so
opt/rocm/lib/libOpenCL.so.1
opt/rocm/lib/libOpenCL.so.1.2
opt/rocm/lib/x86_64/
opt/rocm/lib/x86_64/libOpenCL.so
opt/rocm/lib/x86_64/libOpenCL.so.1
opt/rocm/lib/x86_64/libOpenCL.so.1.2
opt/rocm/lib/x86_64/libamdocl64.so
usr/
usr/share/
usr/share/licenses/
usr/share/licenses/rocm-opencl-runtime/
usr/share/licenses/rocm-opencl-runtime/LICENSE

```
After installing the package,
```
$ /opt/rocm/bin/x86_64/clinfo >/dev/null
ERROR: clGetPlatformIDs(-1001)
```

**Comment by ranisalt** [comment]
Aha, that is because @naetherm removed the patches that put those files into the correct place, and I updated it manually prior to that. I really would like to know why the patches were removed.

**Comment by ranisalt** [comment]
I submitted a patch to fix this upstream RadeonOpenCompute/ROCm-OpenCL-Runtime#111

The ROCm guys said x86_64 part of the path will be removed in a future release, too.

**Comment by tpkessler** [comment]
Oh, I see! What do we do then? Should we merge my version of the PKGBUILD until it's fixed upstream?

**Comment by ranisalt** [comment]
You can add https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/pull/111.patch to the sources array and let that patch handle the fix.

I'll drop the patch files in master so you can rebase against it before we merge.

**Comment by tpkessler** [comment]
I added the patch to the PR. The cmake variable you are using is called `CMAKE_INSTALL_SYSCONFDIR`(with the `FULL`). You may also change this in your upstream patch.

**Comment by ranisalt** [comment]
Thanks!

**Comment by naetherm** [comment]
> Aha, that is because @naetherm removed the patches that put those files into the correct place, and I updated it manually prior to that. I really would like to know why the patches were removed.
> 
> See [a59d761](https://github.com/rocm-arch/rocm-arch/commit/a59d761bdc94e0a671dd0f98f09810fd20c7b9c3)

Sorry for that, I've compiled without using patches in the first place and didn't see any problems.

**Pull request merged**
