### PR TITLE
[rocm-hip-libraries, rocm-hip-sdk] update dependencies to match upstream

### PR DESCRIPTION
**Pull request by wuxxin**
fixes https://github.com/rocm-arch/rocm-arch/issues/845

for easier review i split the update in two commits each,
+ the first commit reorders the current dependencies one per line, alphabetical sorted
+ the second updates this list with the current upstream dependencies

### CODE REVIEW

**Review by acxz — CHANGES_REQUESTED** [review]
The order should be based on whatever source used for determining the dependencies. In this case, the order should be the same as the upstream deb control files, rather than being alphabetical. This is so that it is easier to compare the dependencies if upstream adds/changes them.

**Comment by wuxxin** [comment]
reordered as listed in upstream control file

**Comment by acxz** [comment]
> btw. makepkg --printsrcinfo > .SRCINFO somehow remixes order for unknown reason in .SRCINFO

that's totally fine as `.SRCINFO` is autogenerated

**Review by acxz — APPROVED** [review]

**Comment by tpkessler** [comment]
LGTM! Thanks @wuxxin.

**Review by tpkessler — APPROVED** [review]

**Pull request merged**
