### PR TITLE
hip/hip-hcc: fix typo hip-config -> hipconfig

### PR DESCRIPTION
**Pull request by s-bernard**
Fix a stupid typo for both hip and hip-hcc where hipconfig was written as hip-config.

### CODE REVIEW

**Comment by s-bernard** [comment]
#135

**Comment by acxz** [comment]
@s-bernard have you tested this in a clean chroot?

**Comment by s-bernard** [comment]
What do you mean by clean chroot?

I rebuild the packet from scratch and it did fix the wrong links which is the only modification from previous versions. I currently use this version on my system.

**Comment by acxz** [comment]
https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot

**Pull request merged**
