### PR TITLE
No more need to patch for gfx803

### PR DESCRIPTION
**Pull request by John-Gee**
This undoes the change from #742 .

It seems the patch may not be needed anymore, the runtime variable ROC_ENABLE_PRE_VEGA=1 can do it instead. I verified that it works on my computer but only rebuilt this package.

Thanks!

### CODE REVIEW

**Comment by tpkessler** [comment]
You removed the patch file but didn't update the cmake args. Also, please increase pkgrel, https://wiki.archlinux.org/title/PKGBUILD#Version

**Comment by John-Gee** [comment]
> You removed the patch file but didn't update the cmake args. Also, please increase pkgrel, [wiki.archlinux.org/title/PKGBUILD#Version](https://wiki.archlinux.org/title/PKGBUILD#Version)

Hello,

Sorry about the pkgrel. What do you mean by the cmake args? The original PR did not change those.

Thank you!

**Comment by acxz** [comment]
> What do you mean by the cmake args?

> variable ROC_ENABLE_PRE_VEGA=1 can do it instead

You mention that the above variable can resolve the issue, but shouldn't it be included during the build? This is done by adding the variable to cmake and having it propagate down to whatever logic needs it.

**Comment by John-Gee** [comment]
Oh no, it is a runtime variable not a build time one.

**Comment by tpkessler** [comment]
Thanks for the clarification John!

**Comment by John-Gee** [comment]
Thank you for the merge!

**Pull request merged**
