### PR TITLE
[hsakmt-roct] Allow to build without Supported GPU/Accelerator

### PR DESCRIPTION
**Pull request by fabiscafe**
Changes:
upgpkg: hsakmt-roct 5.4.0-1
    
 * New major release, update checksums
 * skip check()/tests on systems without /dev/kfd (AMD GPU/Accelerator)

This will essentially skip the check() routine if no /dev/kfd was found. This device is only available on systems with amdgpu (kmod) enabled and should be the base-line to make it build.
This change is important to have in build servers, where you might not have a GPU available.

fixes: https://github.com/rocm-arch/rocm-arch/issues/914

### CODE REVIEW

**Comment by tpkessler** [comment]
I agree with you. Do you think that checking for `/dev/kfd` is enough? Doesn't the caller also need to be member of the render group?

**Comment by fabiscafe** [comment]
Hm I'm not sure to if we need this

```
getfacl /dev/kfd /sys/devices/virtual/kfd/kfd/topology/nodes
getfacl: Removing leading '/' from absolute path names
# file: dev/kfd
# owner: root
# group: video
user::rw-
user:fabian:rw-
group::rw-
mask::rw-
other::---
```

Hm I'm not sure about that. it belongs to the video group, so while not render we might need to be part of video. However for some reason my user does have access without being in the video group
```
groups
wheel fabian
``` 
So something did grand me access. It might be my desktop environment/GDM

For the /sys/devices/virtual/kfd/kfd/topology/nodes. If you crawl all the files in there
```
find /sys/devices/virtual/kfd/kfd/topology/nodes -type f -exec getfacl {} \;
```
Thery are readonly to everyone. So if I understand this right we should be fine with the defaults. Here.

**Comment by tpkessler** [comment]
Weird. On my machine:
```
getfacl: Removing leading '/' from absolute path names
# file: dev/kfd
# owner: root
# group: render
user::rw-
group::rw-
other::rw-

# file: sys/devices/virtual/kfd/kfd/topology/nodes
# owner: root
# group: root
user::rwx
group::r-x
other::r-x
```

Nevertheless: Since checking for GPU support is not only an issue of `hsakmt-roct` but of all ROCm packages I've asked internally how this is handled (pytorch and tensorflow have the same issues). The answer was that, since makepkg doesn't support integration tests, an external script is shipped that is manually called by the maintainer after a rebuild. With [a4fb55b](https://github.com/rocm-arch/rocm-arch/commit/a4fb55b4ee2ef2f7c758c029ad9f84fc274bc7c9) I've added a small test script that checks for basic HSA support.

I highly appreciate your PRs, Fabian, as they've been improving ROCm on Arch. I'm sorry I won't merge this one. It would be awesome if you could run `test.sh` on your machine and tell me if it works.

**Comment by fabiscafe** [comment]
> I'm sorry I won't merge this one

Don't be sorry. It's OK. I'll try to test it tomorrow. I'm currently a but busy :)

**Comment by acxz** [comment]
I'm going to close this since we decided not to merge this in. Feel free to comment if you want to continue the conversation.

**Pull request closed without merging**
