### PR TITLE
[rocm-dbgapi] Add missing makedepends for documentation

### LINKED ISSUE #406: [rocm-dbgapi] cmake fails due to missing docs
The installation step for `rocm-dbgabi` fails due to missing docs. This may be related to the latest update to the package that stripped out the docs building step.

```
Install the project...
-- Install configuration: ""
-- Installing: /home/jake/.cache/yay/rocm-dbgapi/pkg/rocm-dbgapi/opt/rocm/lib/librocm-dbgapi.so.0.30.0
-- Installing: /home/jake/.cache/yay/rocm-dbgapi/pkg/rocm-dbgapi/opt/rocm/lib/librocm-dbgapi.so.0
-- Set runtime path of "/home/jake/.cache/yay/rocm-dbgapi/pkg/rocm-dbgapi/opt/rocm/lib/librocm-dbgapi.so.0.30.0" to ""
-- Installing: /home/jake/.cache/yay/rocm-dbgapi/pkg/rocm-dbgapi/opt/rocm/lib/librocm-dbgapi.so
-- Installing: /home/jake/.cache/yay/rocm-dbgapi/pkg/rocm-dbgapi/opt/rocm/include/amd-dbgapi.h
-- Installing: /home/jake/.cache/yay/rocm-dbgapi/pkg/rocm-dbgapi/opt/rocm/share/doc/amd-dbgapi/LICENSE.txt
-- Installing: /home/jake/.cache/yay/rocm-dbgapi/pkg/rocm-dbgapi/opt/rocm/lib/cmake/amd-dbgapi/amd-dbgapi-config.cmake
-- Installing: /home/jake/.cache/yay/rocm-dbgapi/pkg/rocm-dbgapi/opt/rocm/lib/cmake/amd-dbgapi/amd-dbgapi-targets.cmake
-- Installing: /home/jake/.cache/yay/rocm-dbgapi/pkg/rocm-dbgapi/opt/rocm/lib/cmake/amd-dbgapi/amd-dbgapi-targets-noconfig.cmake
CMake Error at cmake_install.cmake:134 (file):
  file INSTALL cannot find
  "/home/jake/.cache/yay/rocm-dbgapi/src/build/doc/html": No such file or
  directory.
```

### PR DESCRIPTION
**Pull request by tpkessler**
Fixes #406 and #404

### CODE REVIEW

**Comment by tpkessler** [comment]
I've checked the debian package: It includes the documentation. This means instead of removing doxygen, we should add it to `makedepends`.

**Comment by acxz** [comment]
Ah then yes let's do that, and I guess then we will need to fix the root error behind #405 
Based on looking at that error it seems that `pdflatex` is needed which is provided by `texlive-bin`.

**Comment by tpkessler** [comment]
Exactly. In addition to `pdflatex` you need additional LaTeX packages, so I had to include the larger `texlive-latexextra` package.

**Comment by acxz** [comment]
Are you able to build it? My build gets stuck.

**Comment by tpkessler** [comment]
Calling pdflatex for the first time may take a while since it needs to generate the font cache first.

**Comment by tpkessler** [comment]
Oh, that got lost in a rebase. I'll add it.

**Pull request merged**
