### PR TITLE
[rocclr] New package

### PR DESCRIPTION
**Pull request by tpkessler**
In preparation for the new `hip` package without `hcc`.

### CODE REVIEW

**Comment by tpkessler** [comment]
It successfully builds in a clean chroot.

**Comment by tpkessler** [comment]
> In preparation for the new hip package without hcc.

and the OpenCL runtime.

**Comment by acxz** [comment]
hmm, is there a need for this package? Based on the debian repos I don't see a `rocclr` package.
http://repo.radeon.com/rocm/apt/debian/pool/main/

**Comment by tpkessler** [comment]
I also looked for a related package but couldn't find one. ROCclr is needed for the new hip and also for compiling the recent OpenCL runtime, so I decided to move it in a separate package.

I think we are in a similar situation as for `llvm-roc`. There was no upstream package but we needed it to compile parts of the ROCm stack. ROCclr is a new package, first released for ROCm 3.5.0. Its former name was vdi which is still present in the documentation for rocm-opencl-runtime. I suspect that AMD uses a different version internally. Looking into the CMakeLists.txt of this project you can see a lot TODOs related to packing. For instance configuration files used for FindPackage() are still missing. That's why I had to manually specify the include paths via `-isystem` for `hip-rocclr`.

**Pull request merged**
